command_timeout = 1000
[directory]
format = "[$path]($style) "
truncation_length = 0
truncation_symbol = ""
truncate_to_repo = false
read_only = " 󰌾"

[username]
style_user = 'white bold'
style_root = 'black bold'
format = ' '
# format = 'user: [$user]($style) '
disabled = false
show_always = true

