#!/usr/bin/env bash

generate_hyprland_colors() {
    local theme_file="$1"
    local theme_name="$2"
    local font="$3"

    # Read colors from environment (already exported by main script)
    cat >~/.config/hypr/colors.conf <<EOFHYPR
# Generated by theme switcher - DO NOT EDIT MANUALLY
# Theme: ${theme_name}

\$background = rgb(${COLOR_BACKGROUND#\#})
\$foreground = rgb(${COLOR_FOREGROUND#\#})
\$accent = rgb(${COLOR_ACCENT#\#})
\$surface = rgb(${COLOR_SURFACE#\#})
\$overlay = rgb(${COLOR_OVERLAY#\#})
\$red = rgb(${COLOR_RED#\#})
\$green = rgb(${COLOR_GREEN#\#})
\$yellow = rgb(${COLOR_YELLOW#\#})
\$blue = rgb(${COLOR_BLUE#\#})
\$magenta = rgb(${COLOR_MAGENTA#\#})
\$cyan = rgb(${COLOR_CYAN#\#})

\$font = ${font}
EOFHYPR

    # Reload Hyprland configuration
    hyprctl reload

    echo "Hyprland colors updated"
}
