---@class utils.icons
local M = {
  ui = {
    Target = "󰀘 ",
    ActiveLSP = " ",
    File = "󰈚 ",
  },
  neotree = {
    git = "󰊢 ",
    buffer = "󰏚 ",
    folder = " ",
  },
  misc = {
    dots = "󰇘",
  },
  formatters = {
    prettierd = "",
    prettier = "",
    autopep8 = "",
    djlint = "",
    shfmt = "",
    ["sql-formatter"] = "󰆼",
    stylua = "",
    fallback = "󰉼",
    black = "",
  },
  dap = {
    Stopped = { "󰁕 ", "DiagnosticWarn", "DapStoppedLine" },
    Breakpoint = " ",
    BreakpointCondition = " ",
    BreakpointRejected = { " ", "DiagnosticError" },
    LogPoint = ".>",
  },
  diagnostics = {
    Error = " ",
    Warn = " ",
    Hint = " ",
    Info = " ",
  },
  git = {
    added = " ",
    modified = " ",
    removed = " ",
  },
  kinds = {
    Array = "󰅪 ",
    BlockMappingPair = "󰅩 ",
    BreakStatement = "󰙧 ",
    Call = "󰃷 ",
    CaseStatement = "󱃙 ",
    Constant = "󰏿 ",
    Constructor = " ",
    ContinueStatement = "→ ",
    Declaration = "󰙠 ",
    Delete = "󰩺 ",
    DoStatement = "󰑖 ",
    Element = "󰅩 ",
    Event = " ",
    Field = " ",
    File = "󰈔 ",
    ForStatement = "󰑖 ",
    GotoStatement = "󰁔 ",
    Identifier = "󰀫 ",
    IfStatement = "󰇉 ",
    Keyword = "󰌋 ",
    List = "󰅪 ",
    Log = "󰦪 ",
    Lsp = " ",
    Macro = "󰁌 ",
    MarkdownH1 = "󰉫 ",
    MarkdownH2 = "󰉬 ",
    MarkdownH3 = "󰉭 ",
    MarkdownH4 = "󰉮 ",
    MarkdownH5 = "󰉯 ",
    MarkdownH6 = "󰉰 ",
    Method = "󰆧 ",
    Module = "󰏗 ",
    Object = "󰅩 ",
    Operator = "󰆕 ",
    Package = "󰆦 ",
    Pair = "󰅪 ",
    Property = " ",
    Regex = " ",
    Repeat = "󰑖 ",
    Return = "󰌑 ",
    Rule = "󰅩 ",
    RuleSet = "󰅩 ",
    Scope = "󰅩 ",
    Section = "󰅩 ",
    Snippet = "󰩫 ",
    Specifier = "󰦪 ",
    Statement = "󰅩 ",
    String = "󰉾 ",
    Struct = " ",
    SwitchStatement = "󰺟 ",
    Table = "󰅩 ",
    Terminal = " ",
    Type = " ",
    TypeParameter = "󰆩 ",
    Unit = " ",

    Text = "󰉿",
    Function = "󰊕",

    WhileStatement = "󰑖 ",

    Class = "󱡠",

    Enum = "󰦨",
    EnumMember = "󰦨",

    Reference = "󰬲",
    Folder = "󰉋",
    Boolean = "󰨙 ",
    Codeium = "󰘦 ",
    Color = " ",
    Control = " ",
    Collapsed = " ",
    -- Copilot = " ",
    Copilot = " ",
    -- Enum = " ",
    -- EnumMember = " ",
    -- Folder = " ",
    -- Function = "󰊕 ",
    Interface = " ",
    Key = " ",
    -- Keyword = " ",
    -- Method = "󰊕 ",
    -- Module = " ",
    Namespace = "󰦮 ",
    Null = " ",
    Number = "󰎠 ",
    -- Operator = " ",
    -- Property = " ",
    -- Reference = " ",
    -- Snippet = " ",
    TabNine = "󰏚 ",
    -- TypeParameter = " ",
    Value = " ",
    Variable = "󰀫 ",
  },
  modes = {
    ["n"] = " ",
    ["no"] = " ",
    ["nov"] = " ",
    ["noV"] = " ",
    ["niI"] = " ",
    ["niR"] = " ",
    ["niV"] = " ",
    ["nt"] = " ",
    ["v"] = "󰈈 ",
    ["vs"] = "󰈈 ",
    ["V"] = "󰈈 ",
    [""] = "󰈈 ",
    ["Vs"] = "󰈈 ",
    ["VB"] = "󰈈 ",
    ["V-BLOCK"] = "󰈈 ",
    ["s"] = " ",
    ["S"] = " ",
    ["i"] = " ",
    ["ic"] = " ",
    ["ix"] = " ",
    ["R"] = "󰛔 ",
    ["Rc"] = "󰛔 ",
    ["Rx"] = "󰛔 ",
    ["Rv"] = "󰛔 ",
    ["Rvc"] = "󰛔 ",
    ["Rvx"] = "󰛔 ",
    ["r"] = "󰛔 ",
    ["c"] = " ",
    ["cv"] = "EX",
    ["ce"] = "EX",
    ["rm"] = "MORE",
    ["r?"] = "CONFIRM",
    ["!"] = " ",
    ["t"] = " ",
  },
  filters = {
    default = {
      "Class",
      "Constructor",
      "Enum",
      "Field",
      "Function",
      "Interface",
      "Method",
      "Module",
      "Namespace",
      "Package",
      "Property",
      "Struct",
      "Trait",
    },
    markdown = false,
    help = false,
    lua = {
      "Class",
      "Constructor",
      "Enum",
      "Field",
      "Function",
      "Interface",
      "Method",
      "Module",
      "Namespace",
      -- "Package", -- remove package since luals uses it for control flow structures
      "Property",
      "Struct",
      "Trait",
    },
  },
}
return M
