return {
  "stevearc/conform.nvim",
  optional = true,
  opts = {
    formatters = {
      ["sql-formatter"] = {
        command = "/home/muizzyranking/.local/share/nvim/mason/bin/sql-formatter",
      },
      -- use semi standard prettier formatter to format.
      ["prettier"] = {
        command = "/home/muizzyranking/.npm-global/bin/prettier-semistandard",
      },
    },
    formatters_by_ft = {
      ["javascript"] = { "prettier" },
      ["javascriptreact"] = { "prettier" },
      ["typescript"] = { "prettier" },
      ["typescriptreact"] = { "prettier" },
      ["vue"] = { "prettier" },
      ["css"] = { "prettierd" },
      ["html"] = { "prettierd" },
      ["scss"] = { "prettier" },
      ["less"] = { "prettier" },
      ["json"] = { "prettier" },
      ["jsonc"] = { "prettier" },
      ["yaml"] = { "prettier" },
      ["markdown"] = { "prettier" },
      ["markdown.mdx"] = { "prettier" },
      ["graphql"] = { "prettier" },
      ["handlebars"] = { "prettier" },
      -- ["javascript"] = { { "prettierd", "prettier" } },
      -- ["javascript"] = { "prettier" },
      -- ["javascriptreact"] = { { "prettierd", "prettier" } },
      -- ["typescript"] = { { "prettierd", "prettier" } },
      -- ["typescriptreact"] = { { "prettierd", "prettier" } },
      -- ["vue"] = { { "prettierd", "prettier" } },
      -- ["css"] = { { "prettierd", "prettier" } },
      -- ["scss"] = { { "prettierd", "prettier" } },
      -- ["less"] = { { "prettierd", "prettier" } },
      -- ["html"] = { { "prettierd", "prettier" } },
      -- ["json"] = { { "prettierd", "prettier" } },
      -- ["jsonc"] = { { "prettierd", "prettier" } },
      -- ["yaml"] = { { "prettierd", "prettier" } },
      -- ["markdown"] = { { "prettierd", "prettier" } },
      -- ["markdown.mdx"] = { { "prettierd", "prettier" } },
      -- ["graphql"] = { { "prettierd", "prettier" } },
      -- ["handlebars"] = { { "prettierd", "prettier" } },
      ["bash"] = { "shfmt" },
      ["zsh"] = { "shfmt" },
      ["sh"] = { "shfmt" },
      ["sql"] = { "sql-formatter" },
    },
  },
}
