gui:
  theme:
    activeBorderColor:
      - "#f5a980"
      - "bold"
    cherryPickedCommitBgColor:
      - "#f0c6c7"
    cherryPickedCommitFgColor:
      - "#8aadf5"
    defaultFgColor:
      - "#cad3f6"
    inactiveBorderColor:
      - "#8aadf5"
    optionsTextColor:
      - "#8aadf5"
    searchingActiveBorderColor:
      - "#f5a980"
      - "bold"
    selectedLineBgColor:
      - "#494d65"
    unstagedChangesColor:
      - "#ed8797"

os:
  editPreset: "nvim"
