lastupdatecheck: 0
recentrepos:
- /home/muizzyranking/dot-files
- /home/muizzyranking/ALX/alx-low_level_programming
- /home/muizzyranking/ALX/AirBnB_clone_v2
- /home/muizzyranking/ALX/alx-system_engineering-devops
- /home/muizzyranking/ALX/alx-higher_level_programming
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
