---@class utils.icons
local M = {
  ui = {
    Target = "󰀘 ",
    ActiveLSP = " ",
    File = "󰈚 ",
  },
  neotree = {
    git = "󰊢 ",
    buffer = "󰏚 ",
    folder = " ",
  },
  misc = {
    dots = "󰇘",
  },
  formatters = {
    prettierd = "",
    prettier = "",
    autopep8 = "",
    djlint = "",
    shfmt = "",
    ["sql-formatter"] = "󰆼",
    stylua = "",
    fallback = "󰉼",
    black = "",
  },
  dap = {
    Stopped = { "󰁕 ", "DiagnosticWarn", "DapStoppedLine" },
    Breakpoint = " ",
    BreakpointCondition = " ",
    BreakpointRejected = { " ", "DiagnosticError" },
    LogPoint = ".>",
  },
  diagnostics = {
    Error = " ",
    Warn = " ",
    Hint = " ",
    Info = " ",
  },
  git = {
    added = " ",
    modified = " ",
    removed = " ",
  },
  kinds = {
    Text = "󰉿",
    Method = "󰊕",
    Function = "󰊕",

    Field = "󰜢",
    Variable = "󰆦",
    Property = "󰖷",

    Class = "󱡠",
    Module = "󰅩",

    Unit = "󰪚",
    Enum = "󰦨",
    EnumMember = "󰦨",

    Keyword = "󰻾",
    Constant = "󰏿",

    Snippet = "󱄽",
    File = "󰈔",
    Reference = "󰬲",
    Folder = "󰉋",
    Operator = "󰪚",
    TypeParameter = "󰬛",
    Array = " ",
    Boolean = "󰨙 ",
    Codeium = "󰘦 ",
    Color = " ",
    Control = " ",
    Collapsed = " ",
    Constructor = " ",
    -- Copilot = " ",
    Copilot = " ",
    -- Enum = " ",
    -- EnumMember = " ",
    Event = " ",
    -- File = " ",
    -- Folder = " ",
    -- Function = "󰊕 ",
    Interface = " ",
    Key = " ",
    -- Keyword = " ",
    -- Method = "󰊕 ",
    -- Module = " ",
    Namespace = "󰦮 ",
    Null = " ",
    Number = "󰎠 ",
    Object = " ",
    -- Operator = " ",
    Package = " ",
    -- Property = " ",
    -- Reference = " ",
    -- Snippet = " ",
    String = " ",
    Struct = "󰆼 ",
    TabNine = "󰏚 ",
    -- TypeParameter = " ",
    Value = " ",
    -- Variable = "󰀫 ",
  },
  modes = {
    ["n"] = " ",
    ["no"] = " ",
    ["nov"] = " ",
    ["noV"] = " ",
    ["niI"] = " ",
    ["niR"] = " ",
    ["niV"] = " ",
    ["nt"] = " ",
    ["v"] = "󰈈 ",
    ["vs"] = "󰈈 ",
    ["V"] = "󰈈 ",
    [""] = "󰈈 ",
    ["Vs"] = "󰈈 ",
    ["VB"] = "󰈈 ",
    ["V-BLOCK"] = "󰈈 ",
    ["s"] = " ",
    ["S"] = " ",
    ["i"] = " ",
    ["ic"] = " ",
    ["ix"] = " ",
    ["R"] = "󰛔 ",
    ["Rc"] = "󰛔 ",
    ["Rx"] = "󰛔 ",
    ["Rv"] = "󰛔 ",
    ["Rvc"] = "󰛔 ",
    ["Rvx"] = "󰛔 ",
    ["r"] = "󰛔 ",
    ["c"] = " ",
    ["cv"] = "EX",
    ["ce"] = "EX",
    ["rm"] = "MORE",
    ["r?"] = "CONFIRM",
    ["!"] = " ",
    ["t"] = " ",
  },
  {
    default = {
      "Class",
      "Constructor",
      "Enum",
      "Field",
      "Function",
      "Interface",
      "Method",
      "Module",
      "Namespace",
      "Package",
      "Property",
      "Struct",
      "Trait",
    },
    markdown = false,
    help = false,
    -- you can specify a different filter for each filetype
    lua = {
      "Class",
      "Constructor",
      "Enum",
      "Field",
      "Function",
      "Interface",
      "Method",
      "Module",
      "Namespace",
      -- "Package", -- remove package since luals uses it for control flow structures
      "Property",
      "Struct",
      "Trait",
    },
  },
}
return M
