---@class utils.icons
return {
  ui = {
    Target = "󰀘 ",
    ActiveLSP = " ",
    File = "󰈚 ",
  },
  neotree = {
    git = "󰊢 ",
    buffer = "󰏚 ",
    folder = " ",
  },
  misc = {
    dots = "󰇘",
  },
  formatters = {
    prettierd = "",
    prettier = "",
    autopep8 = "",
    djlint = "",
    shfmt = "",
    ["sql-formatter"] = "󰆼",
    stylua = "",
    fallback = "󰉼",
  },
  dap = {
    Stopped = { "󰁕 ", "DiagnosticWarn", "DapStoppedLine" },
    Breakpoint = " ",
    BreakpointCondition = " ",
    BreakpointRejected = { " ", "DiagnosticError" },
    LogPoint = ".>",
  },
  diagnostics = {
    Error = " ",
    Warn = " ",
    Hint = " ",
    Info = " ",
  },
  git = {
    added = " ",
    modified = " ",
    removed = " ",
  },
  kinds = {
    Text = "󰉿",
    Method = "󰊕",
    Function = "󰊕",
    Constructor = "󰒓",

    Field = "󰜢",
    Variable = "󰆦",
    Property = "󰖷",

    Class = "󱡠",
    Interface = "󱡠",
    Struct = "󱡠",
    Module = "󰅩",

    Unit = "󰪚",
    Value = "󰦨",
    Enum = "󰦨",
    EnumMember = "󰦨",

    Keyword = "󰻾",
    Constant = "󰏿",

    Snippet = "󱄽",
    Color = "󰏘",
    File = "󰈔",
    Reference = "󰬲",
    Folder = "󰉋",
    Event = "󱐋",
    Operator = "󰪚",
    TypeParameter = "󰬛",
    Array = " ",
    Boolean = "󰨙 ",
    -- Class = " ",
    Codeium = "󰘦 ",
    -- Color = " ",
    Control = " ",
    Collapsed = " ",
    -- Constant = "󰏿 ",
    -- Constructor = " ",
    -- Copilot = " ",
    Copilot = " ",
    -- Enum = " ",
    -- EnumMember = " ",
    -- Event = " ",
    -- Field = " ",
    -- File = " ",
    -- Folder = " ",
    -- Function = "󰊕 ",
    -- Interface = " ",
    Key = " ",
    -- Keyword = " ",
    -- Method = "󰊕 ",
    -- Module = " ",
    Namespace = "󰦮 ",
    Null = " ",
    Number = "󰎠 ",
    Object = " ",
    -- Operator = " ",
    Package = " ",
    -- Property = " ",
    -- Reference = " ",
    -- Snippet = " ",
    String = " ",
    -- Struct = "󰆼 ",
    TabNine = "󰏚 ",
    -- TypeParameter = " ",
    -- Value = " ",
    -- Variable = "󰀫 ",
    Obsidian = " ",
  },
}
